### PR TITLE
Mike urbanski/default vpc filter

### PR DESCRIPTION
**Pull request by mikeurbanski1**
Add filter to ignore groups named "default", which are likely VPC default groups and can't be deleted.

### CODE REVIEW

**Review by nimrodkor — COMMENTED** [review]
@mikeurbanski1 I understand and agree with the idea behind this, but I think it would be better to have it configurable - to be able to filter out the default SG only if I wish. I understand that the default SGs cannot be deleted, but they are still unused. Maybe adding a flag like `--no-default` should be added.
WDYT?

**Comment by mikeurbanski1** [comment]
Agreed. I'll add it. Thanks.

**Comment by mikeurbanski1** [comment]
> @mikeurbanski1 I understand and agree with the idea behind this, but I think it would be better to have it configurable - to be able to filter out the default SG only if I wish. I understand that the default SGs cannot be deleted, but they are still unused. Maybe adding a flag like `--no-default` should be added.
> WDYT?

@nimrodkor This is updated; please take a look.

**Review by schosterbarak — APPROVED** [review]
LGTM 👍 
Thank you @mikeurbanski1 !

**Pull request merged**
